### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by MMMMMz** [LuoUndergradXJTU/TwiBot-22#11]
Hello, may I ask how long it takes you to train the "BotRGCN" model by using the "TWiBOT-22" dataset?
How many graphics cards are needed to perform the experiment efficiently on the "TWiBOT-22" dataset?

**Comment by leopoldwhite** [comment]
Thank you for your interest in our work! 

We trained the BotRGCN model on Twibot22 dataset with one single 12G nvidia 2080ti GPU and the training process itself took about ten minutes.

However, the preprocessing procedure is very time-consuming due to the large scale of Twibot22. Especially, it takes indeed a great amount of time to generate the embedding of user descriptions and user tweets. One approach is to rewrite `Des_embbeding()` and `tweets_embedding()`, enabling it to process user data within a specified range, e.g. extracting tweet embedding for only the 10,000th to 20,000th users. Thus you can process several users' data at the same time by running codes with different range settings simultaneously.

**Comment by MMMMMz** [comment]
Yes, I'm also currently trying to preprocess user descriptions and tweets.
There are two more questions I would like to ask you:
(1) In the BotRGCN model, I checked the code that you directly took the whole picture as input for training without batch division. May I ask if there is no shortage of memory when you use 12G 2080Ti GPU for training?
(2) Does it take 10 minutes to train the "TWiBOT-22" dataset for 200 epochs using BotRGCN?

**Comment by MMMMMz** [comment]
> 

Yes, I'm also currently trying to preprocess user descriptions and tweets.
There are two more questions I would like to ask you:
(1) In the BotRGCN model, I checked the code that you directly took the whole picture as input for training without batch division. May I ask if there is no shortage of memory when you use 12G 2080Ti GPU for training?
(2) Does it take 10 minutes to train the "TWiBOT-22" dataset for 200 epochs using BotRGCN?

**Comment by MMMMMz** [comment]
> Thank you for your interest in our work!
> 
> We trained the BotRGCN model on Twibot22 dataset with one single 12G nvidia 2080ti GPU and the training process itself took about ten minutes.
> 
> However, the preprocessing procedure is very time-consuming due to the large scale of Twibot22. Especially, it takes indeed a great amount of time to generate the embedding of user descriptions and user tweets. One approach is to rewrite `Des_embbeding()` and `tweets_embedding()`, enabling it to process user data within a specified range, e.g. extracting tweet embedding for only the 10,000th to 20,000th users. Thus you can process several users' data at the same time by running codes with different range settings simultaneously.

Yes, I'm also currently trying to preprocess user descriptions and tweets.
There are two more questions I would like to ask you:
(1) In the BotRGCN model, I checked the code that you directly took the whole picture as input for training without batch division. May I ask if there is no shortage of memory when you use 12G 2080Ti GPU for training?
(2) Does it take 10 minutes to train the "TWiBOT-22" dataset for 200 epochs using BotRGCN?

**Comment by leopoldwhite** [comment]
(1) Without batch division, the embedding size of BotRGCN should be no more than 32 for an 12G GPU. To increase the embedding size, it's better to use neighbourloader to divide the whole graph into subgraphs.
(2) Without batch division, the training process of BotRGCN for 200 epochs takes no more than 10 minutes.

**Comment by MMMMMz** [comment]
> (1) Without batch division, the embedding size of BotRGCN should be no more than 32 for an 12G GPU. To increase the embedding size, it's better to use neighbourloader to divide the whole graph into subgraphs. (2) Without batch division, the training process of BotRGCN for 200 epochs takes no more than 10 minutes.

Thank you very much for answering my questions.
