### ISSUE TITLE
How to resolve the RuntimeError?

### ISSUE THREAD

**Issue by MMMMMz** [LuoUndergradXJTU/TwiBot-22#13]
Hello, there was an error in preprocessing user tweet embedding.
The error content is:
RuntimeError: The size of tensor a (802) must match the size of tensor b (512) at non-singleton dimension 1
This happens when working with the 1855 data in the "id_tweet.json" file.
Did the above error occur when you preprocessed the tweet? How did you solve it?

**Comment by BunsenFeng** [comment]
Hi, thank you for your interest in our work! Which baseline method is it? This would help me assign the corresponding individual to help with code issues.

**Comment by MMMMMz** [comment]
> Hi, thank you for your interest in our work! Which baseline method is it? This would help me assign the corresponding individual to help with code issues.

Since the server is out of memory, I split the tweet features into 10 parts to encode them. 
Use the code path “src/twibot22_Botrgcn_feature”. When using "twi0.py" to process tweet features, I used Bert as a pre-trained language model to process tweet encoding, but the above problem occurred when processing the 1855th user tweet.
A similar problem arose with the "TwiBOT-20" dataset. After I deleted all the problematic user tweets, the code worked smoothly;
However, for the "TwiBOT-22" dataset, I still got a "RunTimeError" when I deleted the 1855th user tweet and ran it.

**Comment by BunsenFeng** [comment]
So we are talking about the BotRGCN baseline? I will assign @leopoldwhite to help you.

**Comment by leopoldwhite** [comment]
> > Hi, thank you for your interest in our work! Which baseline method is it? This would help me assign the corresponding individual to help with code issues.
> 
> Since the server is out of memory, I split the tweet features into 10 parts to encode them. Use the code path “src/twibot22_Botrgcn_feature”. When using "twi0.py" to process tweet features, I used Bert as a pre-trained language model to process tweet encoding, but the above problem occurred when processing the 1855th user tweet. A similar problem arose with the "TwiBOT-20" dataset. After I deleted all the problematic user tweets, the code worked smoothly; However, for the "TwiBOT-22" dataset, I still got a "RunTimeError" when I deleted the 1855th user tweet and ran it.

I tested `src/twibot22_Botrgcn_feature/twi0.py` again and didn't encounter this RuntimeError.
And to the best of my knowledge, this kind of RuntimeError is sometimes caused by setting `truncation=False` (_the default value of this parameter is False_).
So have you changed any parameters in this part ?
![image](https://user-images.githubusercontent.com/92447967/184347969-a4b4876b-f1dd-4e47-a4a9-4cfacf1b8bf5.png)

**Comment by MMMMMz** [comment]
> > > Hi, thank you for your interest in our work! Which baseline method is it? This would help me assign the corresponding individual to help with code issues.
> > 
> > 
> > Since the server is out of memory, I split the tweet features into 10 parts to encode them. Use the code path “src/twibot22_Botrgcn_feature”. When using "twi0.py" to process tweet features, I used Bert as a pre-trained language model to process tweet encoding, but the above problem occurred when processing the 1855th user tweet. A similar problem arose with the "TwiBOT-20" dataset. After I deleted all the problematic user tweets, the code worked smoothly; However, for the "TwiBOT-22" dataset, I still got a "RunTimeError" when I deleted the 1855th user tweet and ran it.
> 
> I tested `src/twibot22_Botrgcn_feature/twi0.py` again and didn't encounter this RuntimeError. And to the best of my knowledge, this kind of RuntimeError is sometimes caused by setting `truncation=False` (_the default value of this parameter is False_). So have you changed any parameters in this part ? ![image](https://user-images.githubusercontent.com/92447967/184347969-a4b4876b-f1dd-4e47-a4a9-4cfacf1b8bf5.png)

Hello, I have found a solution to the problem I raised above.
The code screenshot you give contains the "max_length" attribute, which should not be written in "pipeline" but in initializing the "tokenizer".
This solution is useful for me to run code.
The specific writing is shown in the following:

RoBERTa_MODEL_DIR = 'roberta-base'
tokenizer = RobertaTokenizer.from_pretrained(RoBERTa_MODEL_DIR, do_lower_case=True,model_max_length = 64)
config = AutoConfig.from_pretrained(RoBERTa_MODEL_DIR)
model = AutoModel.from_pretrained(BERT_MODEL_DIR)
feature_extract = pipeline('feature-extraction', config=config, model=model,
tokenizer=tokenizer, framework='pt', device = 0,  truncation = True, padding = True, add_special_tokens = True)
