### ISSUE TITLE
Reproducing the GCN/GAT results

### ISSUE THREAD

**Issue by wangqiang-codes** [LuoUndergradXJTU/TwiBot-22#15]
First of all, I deeply appreciate for your work.

I tried to reproduce the results of GCN in the dataset CRESCI-2015.  According to "readme.md" in “GCN_GAT”, I don't know which file to run.

Could you tell me if the node attributes required for GCN come from the preprocessing of BotRGCN? Could you tell me the steps to reproduce the results of GCN starting from the original data?

I downloaded the CRESCI-2015 dataset from Google Drive. Could you tell me how to obtain the "user_text_feats" in the "user_info.pt"?

I look forward to hearing from you.

**Comment by whr000001** [comment]
Hi, thank you for your interest in our work. We update the code of GCN & GAT. You can now run 'train.py' to get the results. We use the same features as BotRGCN. You could get the features from '/src/BotRGCN' and modify the file path in 'dataset.py'. We will update 'readme.md' later. 
If you still have any questions, welcome to ask.

**Comment by wangqiang-codes** [comment]
Thank you for your prompt reply! It works now.
