### ISSUE TITLE
Run out of memory reading Json files

### ISSUE THREAD

**Issue by brunocvs7** [LuoUndergradXJTU/TwiBot-22#17]
Hey, team. I was wondering  how many RAM did you use to read the json files ? It seems that python uses a lot of RAM and I'm  running out of memory too fast, even with 3x the size of the files in RAM (~33GB) available in my OS.

**Comment by whr000001** [comment]
Hi, thank you for your interest in our work. You can use the python package 'ijson' to load these files as an iterator. Here is an example:
`
import ijson
data = ijson.items(open('tweet_0.json', 'r'), 'item') # as an iterator
for item in data:
    do_something(item)
`
And you can get more detailed information at [this website](https://pypi.org/project/ijson/).

**Comment by brunocvs7** [comment]
It worked. Thanks!
