### ISSUE TITLE
requirements.txt 包无法安装

### ISSUE THREAD

**Issue by 37Feng** [LuoUndergradXJTU/TwiBot-22#19]
你好，requirements.txt 文件中存在类似于 absl-py @ file:///opt/conda/conda-bld/absl-py_1639803114343/work 形式的包，在使用pip时无法安装，请问可以更新一下包文件吗？

**Comment by heheyas** [comment]
Hi, thank you for catching this. We have corrected `requirements.txt`.

**Comment by heheyas** [comment]
You can go with the latest version or simply run `pip install -r requirements.txt`. Feel free to post again if you have any questions.

**Comment by 37Feng** [comment]
已解决，非常感谢！！
