### ISSUE TITLE
Inference on new users using BotRGCN

### ISSUE THREAD

**Issue by lkevinzc** [LuoUndergradXJTU/TwiBot-22#20]
Hi authors, thanks for the nice work!

May I know if I have a trained model using BotRGCN, how I could handle new users in the inference phase?

For example, the new user does not exist in the original dataset, do I need to get all its n-degree neighbors and construct a graph first before I can use the model? Is there any recommended way of doing so?

Thanks!

**Comment by TamSiuhin** [comment]
Hi, thanks for your interest in our work! To enable the inductive inference, you do need to induce a subgraph. I recommend you to implement it with torch_geoemetric.NeighborLoader.
