### ISSUE TITLE
Is there sub-communities data in TwiBot-22

### ISSUE THREAD

**Issue by backbp** [LuoUndergradXJTU/TwiBot-22#24]
Appreciate your work! 

The dataset is divided into 10 sub-communities for **Generalization Study**. Could you share the data of sub-communities in TwiBot-22.

Thank you~

**Comment by BunsenFeng** [comment]
Thank you for your interest in our work! I would refer to @whr000001 for this Q.

**Comment by whr000001** [comment]
Thank you for your interest in our work. We upload the sub-communities data in this [directory](https://github.com/LuoUndergradXJTU/TwiBot-22/tree/master/descriptions/sub-communities).

**Comment by backbp** [comment]
Get it. Appreciate your help!

**Comment by backbp** [comment]
I have a question about the sub-community.  The statistics of the 10 sub-communities (table 10 in the paper) indicate the edges of each community are different, but I could not find any information about how to sample edges from the global graph. Looking forward to your reply. @whr000001
