### ISSUE TITLE
Issue on BotRGCN code for cresci-15 dataset

### ISSUE THREAD

**Issue by von1000** [LuoUndergradXJTU/TwiBot-22#26]
Hi! Thank you for sharing your code! I think some of the released code of BotRGCN for cresci-15 is actually for Twibot-22. For example, in train.py and Dataset.py, the data processing module used is class Twibot22.

**Comment by BunsenFeng** [comment]
oh, this is perhaps a typo, @leopoldwhite can you help?

**Comment by leopoldwhite** [comment]
`class Twibot22(Dataset)`  (in `Dataset.py`) is just used to load the processed data generated by `preprocess_1.py` and `preprocess_2.py`
So in `train.py`, both `process` and `save` are set to `False`. And the `dataloader` function of `class Twibot22(Dataset)` can be used for all three datasets.
https://github.com/LuoUndergradXJTU/TwiBot-22/blob/57d32072210420328b5c611d6affe6efd2075980/src/BotRGCN/cresci_15/train.py#L23-L24

**Comment by von1000** [comment]
Thank you!
