### ISSUE TITLE
Low Performance on Most of the Baseline Algorithms

### ISSUE THREAD

**Issue by msharara1998** [LuoUndergradXJTU/TwiBot-22#28]
Hello,
Thank you for your hard efforts in making such a dataset.
I noticed that the performance for most of the baseline algorithms applied on Twibot-22 is very low. Precisely, for the F1 score since it is not a balanced dataset. At the same time, the same algorithms achieve much higher F1 scores in Twibot-20 and other benchmarks.
Is this supposed to be a problem in the dataset itself? What explains this low performance?
Thanks in advance

**Comment by BunsenFeng** [comment]
I agree that this is mostly caused by class imbalance, which is also the case in real-world social media (genuine users >> bots). Maybe a) include ML techniques that combat class imbalance in model training or b) create a subset of TwiBot-22 that is more balanced?

**Comment by msharara1998** [comment]
I'll consider these approaches, thanks!
