### ISSUE TITLE
Ask about the code for "Dataset Format"

### ISSUE THREAD

**Issue by danghieuan** [LuoUndergradXJTU/TwiBot-22#33]
Hello Mr @BunsenFeng ,

Thank you for this great work,
I would like to ask about the code for "transform them into the 4-file format detailed in "Dataset Format"". Does it exist in this repo or not? If not, can I ask for it to see how you convert the original author data to 4-file format detailed in "Dataset Format".

Thank you and best regards,

**Comment by BunsenFeng** [comment]
Hi, I am pinging our dataset format specialist @whr000001 to help you :)

**Comment by danghieuan** [comment]
I understand, special thanks to @BunsenFeng and @whr000001
